name: compress-folders-and-create-releases

on:
  push:
    branches:
      - master

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          zip -r "Buff Charges.zip" modBuffCharges
          zip -r "Grindstone and Workbench Charges Only (modGSaWBC).zip" modGSaWBC
          zip -r "Places of Power Charges Only (modPoPBC).zip" modPoPBC
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mod-zip-files
          path: |
            Buff Charges.zip
            Grindstone and Workbench Charges Only (modGSaWBC).zip
            Places of Power Charges Only (modPoPBC).zip
