name: compress-folders-and-create-releases

on:
  push:
    branches:
      - master

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          zip -r "Buff Charges.zip" modBuffCharges
          zip -r "Grindstone and Workbench Charges Only (modGSaWBC).zip" modGSaWBC
          zip -r "Places of Power Charges Only (modPoPBC).zip" modPoPBC
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mod-zip-files
          path: |
            Buff Charges.zip
            Grindstone and Workbench Charges Only (modGSaWBC).zip
            Places of Power Charges Only (modPoPBC).zip
  create-release:
    needs: compress
    runs-on: ubuntu-latest
    steps:
      # Check out the repository to the virtual machine
      - uses: actions/checkout@v2
      # Manually increment the patch version number based on the number of commits
      - name: Get commit count
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo ::set-output name=commit_count::$COMMIT_COUNT
      - name: Generate SemVer tag
        run: |
          TAG_NAME=v1.0.${{ steps.get_commit_count.outputs.commit_count }}
          echo ::set-output name=tag_name::$TAG_NAME
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_semver_tag.outputs.tag_name }}
          release_name: Release ${{ steps.generate_semver_tag.outputs.tag_name }}
          draft: false
          prerelease: false
          artifact_names: |
            Buff Charges.zip
            Grindstone and Workbench Charges Only (modGSaWBC).zip
            Places of Power Charges Only (modPoPBC).zip
