name: compress-folders-and-create-releases

on:
  push:
    branches:
      - master

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          zip -r "Buff Charges.zip" modBuffCharges
          zip -r "Grindstone and Workbench Charges Only (modGSaWBC).zip" modGSaWBC
          zip -r "Places of Power Charges Only (modPoPBC).zip" modPoPBC
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mod-zip-files
          path: |
            Buff Charges.zip
            Grindstone and Workbench Charges Only (modGSaWBC).zip
            Places of Power Charges Only (modPoPBC).zip
  create-release:
    needs: compress
    runs-on: ubuntu-latest
    steps:
      - name: Generate SemVer tag
        uses: actions/create-semver@v1
        id: semver
        with:
          prefix: v
          version_file: ./.version
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.version }}
          release_name: Release ${{ steps.semver.outputs.version }}
          draft: false
          prerelease: false
          artifact_names: |
            Buff Charges.zip
            Grindstone and Workbench Charges Only (modGSaWBC).zip
            Places of Power Charges Only (modPoPBC).zip
